In [4]:
import pandas as pd
from scipy.stats import ttest_ind 
from scipy.stats import ttest_rel

In [2]:
dataset=pd.read_csv("teen_phone_addiction_dataset.csv")

In [3]:
dataset

,ID,Name,Age,Gender,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
0,1,Shannon Francis,13,Female,Hansonfort,9th,4.0,6.1,78,5,...,1.4,86,19,3.6,1.7,1.2,Browsing,4,8.7,10.0
1,2,Scott Rodriguez,17,Female,Theodorefort,7th,5.5,6.5,70,5,...,0.9,96,9,1.1,4.0,1.8,Browsing,2,5.3,10.0
2,3,Adrian Knox,13,Other,Lindseystad,11th,5.8,5.5,93,8,...,0.5,137,8,0.3,1.5,0.4,Education,6,5.7,9.2
3,4,Brittany Hamilton,18,Female,West Anthony,12th,3.1,3.9,78,8,...,1.4,128,7,3.1,1.6,0.8,Social Media,8,3.0,9.8
4,5,Steven Smith,14,Other,Port Lindsaystad,9th,2.5,6.7,56,4,...,1.0,96,20,2.6,0.9,1.1,Gaming,10,3.7,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,Jesus Yates,16,Female,New Jennifer,12th,3.9,6.4,53,4,...,0.3,80,15,2.7,1.8,1.0,Other,8,9.4,9.8
2996,2997,Bethany Murray,13,Female,Richardport,8th,3.6,7.3,93,5,...,0.9,45,8,3.1,0.0,0.3,Gaming,9,5.2,5.5
2997,2998,Norman Hughes,14,Other,Rebeccaton,7th,3.2,6.5,98,1,...,0.2,51,13,2.4,0.2,2.4,Social Media,9,5.9,6.2
2998,2999,Barbara Hinton,17,Female,Ramirezmouth,9th,6.7,7.5,67,3,...,1.6,125,17,1.7,2.6,1.5,Browsing,4,6.1,10.0
2999,3000,Curtis Johnson,17,Male,Lake Alexander,10th,3.5,6.9,79,4,...,0.6,117,8,0.0,2.3,0.1,Education,7,5.1,6.3

In [ ]:
#INDEPENDENTSAMPLE-UNPAIR
#DIFFERENT GROUP BUT SAME CONDITION

In [5]:
grade9=dataset[dataset['School_Grade']=='9th']['Addiction_Level']
grade10=dataset[dataset['School_Grade']=='10th']['Addiction_Level']
ttest_ind(grade9,grade10)

TtestResult(statistic=0.2490729336822223, pvalue=0.8033549559450139, df=1011.0)

In [ ]:
The p-value (0.803) is greater than 0.05, we fail to reject the null hypothesis. This means there is no statistically significant difference between the Addiction Levels of 9th and 10th grade students.

In [ ]:
#DEPENDENTSAMPLE-PAIR
#SAME GROUP BUT DIFFERENT CONDITION

In [6]:
male=dataset[dataset['Gender']=='Male']['Time_on_Social_Media']
male1=dataset[dataset['Gender']=='Male']['Time_on_Education']
ttest_rel(male,male1)

TtestResult(statistic=39.035728254652184, pvalue=2.7717864719557496e-204, df=1015)

In [ ]:
Since the p-value < 0.05, you reject the null hypothesis.

Interpretation:
There is a statistically significant difference in the time that male spends on social media compared to the time they spend on education.