In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import r2_score

In [35]:
dataset=pd.read_csv("teen_phone_addiction_dataset.csv")

In [36]:
dataset

,ID,Name,Age,Gender,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
0,1,Shannon Francis,13,Female,Hansonfort,9th,4.0,6.1,78,5,...,1.4,86,19,3.6,1.7,1.2,Browsing,4,8.7,10.0
1,2,Scott Rodriguez,17,Female,Theodorefort,7th,5.5,6.5,70,5,...,0.9,96,9,1.1,4.0,1.8,Browsing,2,5.3,10.0
2,3,Adrian Knox,13,Other,Lindseystad,11th,5.8,5.5,93,8,...,0.5,137,8,0.3,1.5,0.4,Education,6,5.7,9.2
3,4,Brittany Hamilton,18,Female,West Anthony,12th,3.1,3.9,78,8,...,1.4,128,7,3.1,1.6,0.8,Social Media,8,3.0,9.8
4,5,Steven Smith,14,Other,Port Lindsaystad,9th,2.5,6.7,56,4,...,1.0,96,20,2.6,0.9,1.1,Gaming,10,3.7,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,Jesus Yates,16,Female,New Jennifer,12th,3.9,6.4,53,4,...,0.3,80,15,2.7,1.8,1.0,Other,8,9.4,9.8
2996,2997,Bethany Murray,13,Female,Richardport,8th,3.6,7.3,93,5,...,0.9,45,8,3.1,0.0,0.3,Gaming,9,5.2,5.5
2997,2998,Norman Hughes,14,Other,Rebeccaton,7th,3.2,6.5,98,1,...,0.2,51,13,2.4,0.2,2.4,Social Media,9,5.9,6.2
2998,2999,Barbara Hinton,17,Female,Ramirezmouth,9th,6.7,7.5,67,3,...,1.6,125,17,1.7,2.6,1.5,Browsing,4,6.1,10.0
2999,3000,Curtis Johnson,17,Male,Lake Alexander,10th,3.5,6.9,79,4,...,0.6,117,8,0.0,2.3,0.1,Education,7,5.1,6.3

In [37]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [38]:
dataset

,ID,Age,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,Exercise_Hours,Anxiety_Level,Depression_Level,Self_Esteem,...,Location_Zavalaton,School_Grade_11th,School_Grade_12th,School_Grade_7th,School_Grade_8th,School_Grade_9th,Phone_Usage_Purpose_Education,Phone_Usage_Purpose_Gaming,Phone_Usage_Purpose_Other,Phone_Usage_Purpose_Social Media
0,1,13,4.0,6.1,78,5,0.1,10,3,8,...,0,0,0,0,0,1,0,0,0,0
1,2,17,5.5,6.5,70,5,0.0,3,7,3,...,0,0,0,1,0,0,0,0,0,0
2,3,13,5.8,5.5,93,8,0.8,2,3,10,...,0,1,0,0,0,0,1,0,0,0
3,4,18,3.1,3.9,78,8,1.6,9,10,3,...,0,0,1,0,0,0,0,0,0,1
4,5,14,2.5,6.7,56,4,1.1,1,5,1,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,16,3.9,6.4,53,4,0.9,7,10,2,...,0,0,1,0,0,0,0,0,1,0
2996,2997,13,3.6,7.3,93,5,0.0,8,8,9,...,0,0,0,0,1,0,0,1,0,0
2997,2998,14,3.2,6.5,98,1,0.0,4,3,9,...,0,0,0,1,0,0,0,0,0,1
2998,2999,17,6.7,7.5,67,3,0.2,3,5,9,...,0,0,0,0,0,1,0,0,0,0
2999,3000,17,3.5,6.9,79,4,2.1,4,5,5,...,0,0,0,0,0,0,1,0,0,0

In [39]:
dataset.columns

Index(['ID', 'Age', 'Daily_Usage_Hours', 'Sleep_Hours', 'Academic_Performance',
       'Social_Interactions', 'Exercise_Hours', 'Anxiety_Level',
       'Depression_Level', 'Self_Esteem',
       ...
       'Location_Zavalaton', 'School_Grade_11th', 'School_Grade_12th',
       'School_Grade_7th', 'School_Grade_8th', 'School_Grade_9th',
       'Phone_Usage_Purpose_Education', 'Phone_Usage_Purpose_Gaming',
       'Phone_Usage_Purpose_Other', 'Phone_Usage_Purpose_Social Media'],
      dtype='object', length=5688)

In [41]:
independent=dataset[['Daily_Usage_Hours', 'Phone_Checks_Per_Day', 'Apps_Used_Daily',
       'Time_on_Social_Media', 'Time_on_Gaming']]

In [42]:
dependent=dataset[['Addiction_Level']]

In [43]:
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [44]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [45]:
regressor=SVR(kernel="rbf")
regressor.fit(X_train,Y_train)
y_pred=regressor.predict(X_test)

C:\Users\jegat\Anaconda3\envs\cluster\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [46]:
r_score=r2_score(Y_test,y_pred)

In [47]:
r_score

0.8847327002997564

In [54]:
with open("sc.pkl","wb") as f:
    pickle.dump(sc,f)

In [55]:
import pickle
#filename="finalized_model_svr.sav"
with open("finalized_model_svr.sav","wb") as f: 
#pickle.dump(regressor,open(filename,'wb'))
    pickle.dump(regressor,f)

In [56]:
with open("sc.pkl","rb") as f:
    loaded_sc=pickle.load(f)

In [57]:
with open("finalized_model_svr.sav","rb") as f:
    loaded_model=pickle.load(f)

In [58]:
preinput=loaded_sc.transform([[3.6,96,17,3.1,2.0]])
preinput

C:\Users\jegat\Anaconda3\envs\cluster\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-0.71425809,  0.36673957,  0.96439794,  0.60727299,  0.48670855]])

In [59]:
#loaded_model=pickle.load(open("finalized_model_svr.sav",'rb'))
result=loaded_model.predict(preinput)

In [61]:
result

array([9.99181512])